# Generated by Django 4.1.2 on 2022-10-17 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_imagen_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen_producto',
            field=models.ImageField(blank=True, max_length=150, null=True, upload_to='productos//'),
        ),
    ]
