# Generated by Django 3.2.3 on 2021-07-20 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(default=19),
        ),
    ]
