# Generated by Django 3.2.3 on 2021-07-21 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_alter_factura_iva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='boleta',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='subtotal',
        ),
    ]
